// Mocks generated by Mockito 5.4.6 from annotations
// in saturday_app/test/widgets/tags/rfid_connection_modal_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:saturday_app/models/lock_result.dart' as _i4;
import 'package:saturday_app/models/serial_connection_state.dart' as _i2;
import 'package:saturday_app/models/tag_poll_result.dart' as _i8;
import 'package:saturday_app/models/write_result.dart' as _i3;
import 'package:saturday_app/services/serial_port_service.dart' as _i5;
import 'package:saturday_app/services/uhf_rfid_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSerialConnectionState_0 extends _i1.SmartFake
    implements _i2.SerialConnectionState {
  _FakeSerialConnectionState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteResult_1 extends _i1.SmartFake implements _i3.WriteResult {
  _FakeWriteResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLockResult_2 extends _i1.SmartFake implements _i4.LockResult {
  _FakeLockResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SerialPortService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialPortService extends _i1.Mock implements _i5.SerialPortService {
  MockSerialPortService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i2.SerialConnectionState> get stateStream =>
      (super.noSuchMethod(
            Invocation.getter(#stateStream),
            returnValue: _i6.Stream<_i2.SerialConnectionState>.empty(),
          )
          as _i6.Stream<_i2.SerialConnectionState>);

  @override
  _i6.Stream<List<int>> get dataStream =>
      (super.noSuchMethod(
            Invocation.getter(#dataStream),
            returnValue: _i6.Stream<List<int>>.empty(),
          )
          as _i6.Stream<List<int>>);

  @override
  _i2.SerialConnectionState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSerialConnectionState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.SerialConnectionState);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get isModuleEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isModuleEnabled),
            returnValue: false,
          )
          as bool);

  @override
  List<String> getAvailablePorts() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailablePorts, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Map<String, String> getPortInfo(String? portName) =>
      (super.noSuchMethod(
            Invocation.method(#getPortInfo, [portName]),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i6.Future<bool> connect(String? portName, {int? baudRate}) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [portName], {#baudRate: baudRate}),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> write(List<int>? data) =>
      (super.noSuchMethod(
            Invocation.method(#write, [data]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void setModuleEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setModuleEnabled, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UhfRfidService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUhfRfidService extends _i1.Mock implements _i7.UhfRfidService {
  MockUhfRfidService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get isModuleEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isModuleEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Stream<_i2.SerialConnectionState> get connectionStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStateStream),
            returnValue: _i6.Stream<_i2.SerialConnectionState>.empty(),
          )
          as _i6.Stream<_i2.SerialConnectionState>);

  @override
  _i2.SerialConnectionState get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _FakeSerialConnectionState_0(
              this,
              Invocation.getter(#connectionState),
            ),
          )
          as _i2.SerialConnectionState);

  @override
  List<int> get accessPassword =>
      (super.noSuchMethod(
            Invocation.getter(#accessPassword),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i6.Stream<_i8.TagPollResult> get pollStream =>
      (super.noSuchMethod(
            Invocation.getter(#pollStream),
            returnValue: _i6.Stream<_i8.TagPollResult>.empty(),
          )
          as _i6.Stream<_i8.TagPollResult>);

  @override
  bool get isPolling =>
      (super.noSuchMethod(Invocation.getter(#isPolling), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> connect(String? port, {int? baudRate}) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [port], {#baudRate: baudRate}),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> setRfPower(int? dbm) =>
      (super.noSuchMethod(
            Invocation.method(#setRfPower, [dbm]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<int?> getRfPower() =>
      (super.noSuchMethod(
            Invocation.method(#getRfPower, []),
            returnValue: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  void setAccessPassword(List<int>? password) => super.noSuchMethod(
    Invocation.method(#setAccessPassword, [password]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> startPolling() =>
      (super.noSuchMethod(
            Invocation.method(#startPolling, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> stopPolling() =>
      (super.noSuchMethod(
            Invocation.method(#stopPolling, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i8.TagPollResult>> singlePoll() =>
      (super.noSuchMethod(
            Invocation.method(#singlePoll, []),
            returnValue: _i6.Future<List<_i8.TagPollResult>>.value(
              <_i8.TagPollResult>[],
            ),
          )
          as _i6.Future<List<_i8.TagPollResult>>);

  @override
  _i6.Future<_i3.WriteResult> writeEpc(List<int>? newEpc) =>
      (super.noSuchMethod(
            Invocation.method(#writeEpc, [newEpc]),
            returnValue: _i6.Future<_i3.WriteResult>.value(
              _FakeWriteResult_1(this, Invocation.method(#writeEpc, [newEpc])),
            ),
          )
          as _i6.Future<_i3.WriteResult>);

  @override
  _i6.Future<bool> verifyEpc(
    List<int>? expectedEpc, {
    Duration? timeout = const Duration(seconds: 2),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEpc, [expectedEpc], {#timeout: timeout}),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i4.LockResult> lockTag(List<int>? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#lockTag, [newPassword]),
            returnValue: _i6.Future<_i4.LockResult>.value(
              _FakeLockResult_2(
                this,
                Invocation.method(#lockTag, [newPassword]),
              ),
            ),
          )
          as _i6.Future<_i4.LockResult>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
